CREATE TABLE BBS22
(	"no" VARCHAR2(100), 
	"TITLE" VARCHAR2(100), 
	"CONTENT" VARCHAR2(100), 
	"WRITER" VARCHAR2(100), 
	 CONSTRAINT "BBS_PK23" PRIMARY KEY ("no"),
	 CONSTRAINT "FK_MEMBER23" FOREIGN KEY ("WRITER")
	  REFERENCES "HR"."MEMBER" ("ID")
) 

CREATE TABLE BBS3
(	NO VARCHAR2(100), 
	TITLE VARCHAR2(100), 
	CONTENT VARCHAR2(100), 
	WRITER VARCHAR2(100)
) 

-- pk제약조건 추가 

ALTER TABLE HR.BBS3
ADD CONSTRAINT BBS3_PK 
PRIMARY KEY (NO)

-- kf제약조건 추가

ALTER TABLE HR.BBS3 
ADD CONSTRAINT FK_MEMBER33 
FOREIGN KEY (WRITER) REFERENCES HR."MEMBER"(ID);




CREATE TABLE depart2 (
	id varchar2(100),
	name varchar2(100),
	instructor varchar2(100),
	CONSTRAINT PK_DEPART2 PRIMARY KEY (id)
)

CREATE TABLE student2 (
	id varchar2(100),
	name varchar2(100),
	depart_id varchar2(100)
)

ALTER TABLE STUDENT2 
ADD CONSTRAINTS pk_st2 
PRIMARY KEY (id)

ALTER TABLE STUDENT2 
ADD CONSTRAINTS fk_st2
FOREIGN KEY (depart_id)
REFERENCES depart2 (id)