CREATE TABLE PRODUCT3
   (	"ID" VARCHAR2(200), 
	"NAME" VARCHAR2(200), 
	"CONTENT" VARCHAR2(200), 
	"PRICE" NUMBER(38,0), 
	"COMPANY" VARCHAR2(200), 
	"IMG" VARCHAR2(200)
   )
   
-- 연습문제2
SELECT * FROM PRODUCT3
ORDER BY PRICE DESC

-- 연습문제3
SELECT NAME, CONTENT, PRICE FROM PRODUCT3
ORDER BY COMPANY

-- 연습문제4
SELECT DISTINCT COMPANY FROM PRODUCT3

-- 연습문제5
SELECT PRICE*5 AS PRICE5 FROM PRODUCT3

-- 연습문제6
SELECT NAME, COMPANY FROM PRODUCT3 WHERE PRICE = 5000

-- 연습문제7
SELECT PRICE, COMPANY FROM PRODUCT3 WHERE PRICE BETWEEN 3000 AND 6000

-- 연습문제8
SELECT COMPANY, NAME FROM PRODUCT3 WHERE COMPANY != 'c100'

-- 연습문제9
SELECT NAME, PRICE FROM PRODUCT3 WHERE COMPANY IN ('c100', 'c200')

-- 연습문제10
SELECT * FROM PRODUCT3 WHERE NAME LIKE '%4'

-- 연습문제11
SELECT * FROM PRODUCT3 WHERE CONTENT LIKE '%food%'

-- 연습문제12
UPDATE PRODUCT3 SET CONTENT = '품절' WHERE PRICE = 5000

-- 연습문제13
UPDATE PRODUCT3 SET IMG = 'o.png', PRICE = 10000 WHERE ID IN ('100', '102')

-- 연습문제14
DELETE FROM PRODUCT3 WHERE COMPANY = 'c100'

-- 연습문제15
DELETE FROM PRODUCT3

