CREATE TABLE "HR"."PRODUCT2" 
   (	"ID" VARCHAR2(100) PRIMARY KEY, 
	"NAME" VARCHAR2(100), 
	"CONTENT" VARCHAR2(100), 
	"PRICE" NUMBER(38,0)
   )
   
   
CREATE TABLE "HR"."PRODUCT3" 
(	"ID" VARCHAR2(100) PRIMARY KEY, 
	"NAME" VARCHAR2(100), 
	"CONTENT" VARCHAR2(100), 
	"PRICE" NUMBER(38,0)
)
   
   
   INSERT INTO MEMBER VALUES('100', '100', 'PARK', '011')

   INSERT INTO MEMBER VALUES('200', '300', 'KIM', '012')
   
   INSERT INTO MEMBER VALUES('12', '200', 'KL', '010')
                                
   SELECT * FROM "MEMBER" 
   
   SELECT * FROM "MEMBER" WHERE ID='100'		-- ID가 100인 모든 컬럼
   
   SELECT ID, NAME FROM "MEMBER"  WHERE ID='100'
   
   SELECT TEL FROM "MEMBER" WHERE NAME = 'PARK'
   
   UPDATE  "MEMBER" SET PW='8888', TEL = '9999' WHERE ID = 'ICE'
   
   DELETE FROM "MEMBER" WHERE ID = '100'
   
   DELETE FROM MEMBER WHERE tel = '011'

	SELECT * FROM MEMBER WHERE id = '200' AND tel = '011'
	
	SELECT * FROM MEMBER WHERE id = '200' or tel = '011'


	DROP TABLE PRODUCT 
	
	DROP TABLE PRODUCT2 

	DROP TABLE PRODUCT3 