-- 피드 
-- 아이디, 내용, 작성일자 DATE, 조회수 NUMBER, 좋아요 NUMBER
CREATE TABLE FEED (
	ID VARCHAR2(100),
	CONTENT VARCHAR2(100),
	WRITEDATE DATE,
	조회수 NUMBER(38,0),
	좋아요 NUMBER (38,0)
)


-- 사용자
-- 아이디, 이메일, 이름, 전화번호
CREATE TABLE USERS(
	ID VARCHAR2(100),
	EMAIL VARCHAR2(100),
	NAME VARCHAR2(100),
	PHONE VARCHAR2(100)
)

UPDATE FEED SET 조회수 = 100 WHERE FEEDID='FEED01'

INSERT INTO USERS VALUES('USER03', 'hi@gmail.com', '김철수', '010-1234-1234')

SELECT * FROM FEED f  
INNER JOIN USERS u 
ON (f.WRITER  = u.ID)

SELECT u.ID, u.NAME FROM FEED f
RIGHT OUTER JOIN USERS u 
ON (u.ID = f.WRITER)
