-- 집계/그룹 함수

SELECT count(MGR) FROM EMP	--null제외 13개

SELECT count(*) FROM EMP	

SELECT COUNT(SAL), SUM(SAL) FROM EMP WHERE JOB='SALESMAN'

SELECT MIN(SAL), AVG(SAL), MAX(SAL) FROM EMP WHERE JOB='SALESMAN'

SELECT JOB, COUNT(SAL), SUM(SAL), AVG(SAL) FROM EMP
GROUP BY JOB

SELECT JOB, COUNT(SAL), SUM(SAL), ROUND(AVG(SAL)), MIN(SAL), MAX(SAL) FROM EMP
GROUP BY JOB
HAVING COUNT(SAL) >= 4
ORDER BY JOB DESC


-- 정리문제 1
SELECT COUNT(*) FROM EMP

-- 정리문제 2
SELECT COUNT(*) FROM EMP WHERE DEPTNO = 20 OR MGR <= 7700

-- 정리문제 3
SELECT MIN(SAL) FROM EMP WHERE DEPTNO IN (10, 20)

-- 정리문제 4
SELECT MIN(SAL), MAX(SAL), SUM(SAL) FROM EMP 

-- 정리문제 5
SELECT DEPTNO, AVG(SAL) FROM EMP GROUP BY DEPTNO

-- 정리문제 6
SELECT DEPTNO, SUM(SAL) FROM EMP GROUP BY DEPTNO ORDER BY DEPTNO

-- 정리문제 7
SELECT DEPTNO, ROUND(AVG(SAL)) FROM EMP 
GROUP BY DEPTNO 
HAVING AVG(SAL)>=2000  
ORDER BY DEPTNO DESC

-- 정리문제 8
SELECT COUNT(*), ROUND(AVG(SAL)) FROM EMP WHERE JOB='MANAGER'

-- 정리문제 9
SELECT COUNT(*) FROM EMP WHERE ENAME LIKE '%S%'

-- 정리문제 10
SELECT COUNT(*) FROM EMP WHERE SAL>=3000 AND COMM IS NOT NULL 
ORDER BY SAL DESC